#Author: Nandan Desai
version: "2"
services:
    db:
        image: mariadb:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./database:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - PMA_HOST=db
        restart: always
        ports:
            - 8000:80
        links:
            - db:db
    web:
        build: .
        # The :Z flag at the end is for SELinux permissions
        volumes:
            - ./web:/var/www/html:Z
            - ./logs:/var/log/apache2:Z
        links:
            - db
        ports:
            - 8080:80
        security_opt:
            - label:disable
        tty: true
